/*
// * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package deliveryapp;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;
import javax.swing.table.*;

        
/**
 *
 * @author Shazin
 */
public class CustomerGUI extends javax.swing.JFrame {
    private DefaultTableModel model = new DefaultTableModel();
    private String[] column = {"ID", "Item Name", "Description", "Price"};
    Customer loggedIn;
    
    /**
     * Creates new form CustomerGUI
     */
    public CustomerGUI(String username, String password, int balance, String location) {
        initComponents();
        loggedIn = new Customer(username, password, balance);
        loggedIn.setLocation(location);
        lb_welcome.setText("Welcome "+username);
        
        model.setColumnIdentifiers(column);
        parseMenu();
        
        
    }
    
    //Testing
    private CustomerGUI() {
        initComponents();
        model.setColumnIdentifiers(column);
        adjustColumnWidths();
        parseMenu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_welcome = new javax.swing.JLabel();
        bt_cart = new javax.swing.JButton();
        bt_orders = new javax.swing.JButton();
        bt_vendor1 = new javax.swing.JButton();
        bt_vendor2 = new javax.swing.JButton();
        bt_vendor3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_menu = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lb_welcome.setText("Welcome Customer");

        bt_cart.setText("View cart");
        bt_cart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cartActionPerformed(evt);
            }
        });

        bt_orders.setText("Orders");

        bt_vendor1.setText("Vendor 1");
        bt_vendor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_vendor1ActionPerformed(evt);
            }
        });

        bt_vendor2.setText("Vendor 2");
        bt_vendor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_vendor2ActionPerformed(evt);
            }
        });

        bt_vendor3.setText("Vendor 3");

        tb_menu.setModel(model);
        tb_menu.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(tb_menu);
        tb_menu.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jButton1.setText("Reviews");

        jButton2.setText("Add to cart");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bt_orders, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bt_vendor1)
                            .addComponent(bt_vendor3)
                            .addComponent(bt_vendor2))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(lb_welcome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 247, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(bt_cart, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2))
                        .addGap(18, 18, 18))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_orders)
                    .addComponent(lb_welcome)
                    .addComponent(bt_cart))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bt_vendor1)
                        .addGap(31, 31, 31)
                        .addComponent(bt_vendor2)
                        .addGap(28, 28, 28)
                        .addComponent(bt_vendor3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void adjustColumnWidths() {
        TableColumnModel columnModel = tb_menu.getColumnModel();

        // Set the preferred width for specific columns
        columnModel.getColumn(0).setPreferredWidth(30); // ID column
        columnModel.getColumn(1).setPreferredWidth(150); // Item column
        columnModel.getColumn(2).setPreferredWidth(250); // Description column
        columnModel.getColumn(3).setPreferredWidth(30); // Price column
    }
    private void parseMenu() {
                try {
            Scanner scanner = new Scanner(new File("C:\\Users\\Shazin\\OneDrive - Asia Pacific University\\University\\Year 2\\Java\\Assignment\\DeliveryApp\\src\\deliveryapp\\data\\menu.txt"));
            
            while (scanner.hasNextLine()) {
                String line = scanner.nextLine();
                String[] parts = line.split(";");
                
                // The first part is always the vendor name
                String vendorName = parts[0].trim();
                System.out.println("Vendor: " + vendorName);
                
                // Subsequent parts are menu items
                for (int i = 1; i < parts.length; i++) {
                    String[] itemDetails = parts[i].split("\\|");
                    
                    if (itemDetails.length == 4) {
                        int itemId = Integer.parseInt(itemDetails[0]);
                        String itemName = itemDetails[1].trim();
                        String description = itemDetails[2].trim();
                        int price = Integer.parseInt(itemDetails[3]);
                        
                        System.out.println("  Item ID: " + itemId);
                        System.out.println("  Item Name: " + itemName);
                        System.out.println("  Description: " + description);
                        System.out.println("  Price: " + price);
                        System.out.println(); // Add a newline for better readability
                        model.addRow(new Object[]{itemId, itemName, description, price});
                        
                    } else {
                        System.out.println("Invalid item format: " + parts[i]);
                    }
                }
            }
            
            scanner.close();
        } catch (FileNotFoundException ex) {
            ex.printStackTrace();
        }
    }
    
    private void bt_vendor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_vendor1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_vendor1ActionPerformed

    private void bt_vendor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_vendor2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_vendor2ActionPerformed

    private void bt_cartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_cartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_cart;
    private javax.swing.JButton bt_orders;
    private javax.swing.JButton bt_vendor1;
    private javax.swing.JButton bt_vendor2;
    private javax.swing.JButton bt_vendor3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_welcome;
    private javax.swing.JTable tb_menu;
    // End of variables declaration//GEN-END:variables
}
